name: Java CI Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: ☑️ Checkout
        uses: actions/checkout@v7
      - name: ☕ Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
          cache: 'gradle'
      - name: 🏗️ Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: 🏗️ Publish with Gradle
        run: ./gradlew publishJar --stacktrace
        env:
          JRELEASER_MAVENCENTRAL_STAGE: "FULL"
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: "-"
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
